name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/release.yaml@ce6415046b541e5f000a3a6c3390916b6abf4e30 # v1.2.4
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
